import React, { Component } from 'react';
import style from './pages.css';

class HomePage extends Component {
  render() {
    return (
      <div>
        HomePage
        
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      <div>
        HomePage
      </div>
      </div>
    )
  }
}

export default HomePage;